// food_order_admin/src/features/menu/views/MenuView.vue
<script setup lang="ts">
import { useMenuStore } from '../stores/menu_store';
import {
  Plus,
  Search,
  Star,
  Clock,
  Flame,
  Edit2,
  Trash2,
  CheckCircle2,
  AlertCircle,
} from 'lucide-vue-next';

const menuStore = useMenuStore();
</script>

<template>
  <div class="space-y-6">
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
      <div>
        <h2 class="text-xl font-bold font-display text-white">Menu & Food Catalog</h2>
        <p class="text-xs text-slate-400">
          Manage kitchen dishes, pricing, inventory stock availability and recipes
        </p>
      </div>

      <div class="flex items-center gap-3">
        <button
          @click="menuStore.openAddFoodModal()"
          class="px-4 py-2.5 rounded-xl bg-gradient-to-r from-orange-500 to-amber-500 hover:brightness-110 text-white text-xs font-bold shadow-lg shadow-orange-500/20 flex items-center gap-1.5 transition active:scale-95"
        >
          <Plus class="w-4 h-4" />
          <span>Add New Dish</span>
        </button>
      </div>
    </div>

    <div class="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-3">
      <div class="flex items-center gap-1.5 overflow-x-auto pb-1">
        <button
          @click="menuStore.selectedCategory = 'All'"
          :class="[
            'px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition border',
            menuStore.selectedCategory === 'All'
              ? 'bg-orange-500/15 border-orange-500/40 text-orange-400'
              : 'bg-slate-900/60 border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800/60'
          ]"
        >
          All Items ({{ menuStore.foods.length }})
        </button>
        <button
          v-for="cat in menuStore.categories"
          :key="cat.id"
          @click="menuStore.selectedCategory = cat.name"
          :class="[
            'px-3 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition border',
            menuStore.selectedCategory === cat.name
              ? 'bg-orange-500/15 border-orange-500/40 text-orange-400'
              : 'bg-slate-900/60 border-slate-800 text-slate-400 hover:text-white hover:bg-slate-800/60'
          ]"
        >
          {{ cat.name }}
        </button>
      </div>

      <div class="relative w-full md:w-64">
        <Search class="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
        <input
          v-model="menuStore.searchQuery"
          type="text"
          placeholder="Search recipes, tags..."
          class="w-full bg-slate-800/80 border border-slate-700/80 rounded-xl pl-9 pr-4 py-1.5 text-xs text-slate-200 placeholder-slate-400 focus:outline-none focus:border-orange-500"
        />
      </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      <div
        v-for="item in menuStore.filteredFoods"
        :key="item.id"
        class="glass-card rounded-2xl overflow-hidden border border-slate-800/80 hover:border-slate-700 transition flex flex-col justify-between group"
      >
        <div class="relative h-44 w-full overflow-hidden bg-slate-800">
          <img
            :src="item.image"
            :alt="item.name"
            class="w-full h-full object-cover group-hover:scale-105 transition duration-300"
          />
          <div class="absolute inset-0 bg-gradient-to-t from-slate-950 via-transparent to-transparent opacity-60" />

          <span class="absolute top-2.5 left-2.5 text-[10px] font-semibold px-2 py-0.5 rounded-lg bg-slate-900/80 backdrop-blur-md text-slate-200 border border-white/10">
            {{ item.category }}
          </span>

          <div class="absolute top-2.5 right-2.5 flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded-lg bg-slate-900/80 backdrop-blur-md text-amber-400 border border-white/10">
            <Star class="w-3 h-3 fill-amber-400" />
            <span>{{ item.rating }}</span>
          </div>

          <div class="absolute bottom-2.5 left-2.5">
            <span class="text-base font-bold font-display text-white bg-slate-900/90 backdrop-blur-md px-2.5 py-1 rounded-xl border border-white/10 text-orange-400">
              ${{ item.price.toFixed(2) }}
            </span>
          </div>
        </div>

        <div class="p-4 flex-1 flex flex-col justify-between">
          <div>
            <h3 class="text-sm font-bold text-white group-hover:text-orange-400 transition truncate">
              {{ item.name }}
            </h3>
            <p class="text-xs text-slate-400 line-clamp-2 mt-1 leading-relaxed">
              {{ item.description }}
            </p>

            <div class="flex items-center gap-3 mt-3 text-[11px] text-slate-400">
              <span class="flex items-center gap-1">
                <Clock class="w-3 h-3 text-orange-400" />
                {{ item.prepTimeMinutes }}m prep
              </span>
              <span v-if="item.calories" class="flex items-center gap-1">
                <Flame class="w-3 h-3 text-amber-400" />
                {{ item.calories }} kcal
              </span>
            </div>

            <div class="flex flex-wrap gap-1 mt-2.5">
              <span
                v-for="tag in item.tags"
                :key="tag"
                class="text-[9px] font-semibold px-2 py-0.5 rounded-md bg-slate-800 text-slate-300 border border-slate-700/60"
              >
                {{ tag }}
              </span>
            </div>
          </div>

          <div class="pt-4 mt-4 border-t border-slate-800/80 flex items-center justify-between">
            <button
              @click="menuStore.toggleAvailability(item.id)"
              :class="[
                'flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-xl transition border',
                item.isAvailable
                  ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20 hover:bg-emerald-500/20'
                  : 'bg-rose-500/10 text-rose-400 border-rose-500/20 hover:bg-rose-500/20'
              ]"
            >
              <CheckCircle2 v-if="item.isAvailable" class="w-3 h-3" />
              <AlertCircle v-else class="w-3 h-3" />
              <span>{{ item.isAvailable ? 'In Stock' : 'Sold Out' }}</span>
            </button>

            <div class="flex items-center gap-1">
              <button
                @click="menuStore.openEditFoodModal(item)"
                class="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition"
                title="Edit item"
              >
                <Edit2 class="w-3.5 h-3.5" />
              </button>
              <button
                @click="menuStore.deleteFood(item.id)"
                class="p-1.5 rounded-lg bg-slate-800 hover:bg-rose-900/40 text-slate-300 hover:text-rose-400 transition"
                title="Delete item"
              >
                <Trash2 class="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// food_order_web/src/features/menu/menu_view.jsx
import { useEffect } from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { useTranslation } from '../../core';
import { AppRoutes, getCategoryDetailRoute } from '../../routes/app_routes';
import { FoodCard } from './components/FoodCard';
import { FoodDetailModal } from './components/FoodDetailModal';
import { useMenuStore } from './menu_store';
import { MenuIntent } from './menu_intent';

export function MenuView() {
  const { t } = useTranslation();
  const [searchParams, setSearchParams] = useSearchParams();
  const urlQuery = searchParams.get('q') || '';
  const urlCategory = searchParams.get('category') || 'ALL';

  const { state, onIntent, processedFoods } = useMenuStore({
    selectedCategory: urlCategory,
    searchQuery: urlQuery,
  });

  const { foods, categories, sortBy, loading, selectedFood, selectedCategory, searchQuery } = state;

  // Synchronize URL changes to MVI Store
  useEffect(() => {
    onIntent(MenuIntent.setCategory(urlCategory));
  }, [urlCategory, onIntent]);

  useEffect(() => {
    onIntent(MenuIntent.setSearch(urlQuery));
  }, [urlQuery, onIntent]);

  const handleCategoryChange = (categoryName) => {
    const newParams = new URLSearchParams(searchParams);
    if (categoryName === 'ALL') {
      newParams.delete('category');
    } else {
      newParams.set('category', categoryName);
    }
    setSearchParams(newParams);
    onIntent(MenuIntent.setCategory(categoryName));
  };

  const handleSearchChange = (e) => {
    const val = e.target.value;
    const newParams = new URLSearchParams(searchParams);
    if (!val.trim()) {
      newParams.delete('q');
    } else {
      newParams.set('q', val);
    }
    setSearchParams(newParams);
    onIntent(MenuIntent.setSearch(val));
  };

  return (
    <div className="space-y-6 sm:space-y-8 pb-8">
      {/* Header Banner */}
      <div className="rounded-2xl sm:rounded-3xl bg-gradient-to-r from-orange-500/10 via-amber-500/5 to-transparent p-4 sm:p-8 border border-orange-500/20 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-slate-900 dark:text-white">
            {t('menu.menuTitle')}
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1 max-w-2xl">
            {t('menu.menuSubtitle')}
          </p>
        </div>

        <Link
          to={AppRoutes.CATEGORIES}
          className="inline-flex items-center space-x-1.5 px-4 py-2.5 rounded-2xl bg-white dark:bg-slate-800 text-orange-600 dark:text-orange-400 text-xs font-bold border border-orange-200 dark:border-orange-900/60 shadow-xs hover:border-orange-500 transition-all shrink-0 self-start sm:self-auto"
        >
          <span>✨</span>
          <span>{t('categories.allCategories')}</span>
          <span>→</span>
        </Link>
      </div>

      {/* Filter and Search Controls */}
      <div className="bg-white dark:bg-slate-900 p-3.5 sm:p-5 rounded-2xl sm:rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xs space-y-3 sm:space-y-4">
        {/* Search & Sort Controls */}
        <div className="flex flex-col sm:flex-row gap-2.5 sm:gap-3 items-stretch sm:items-center justify-between">
          {/* Search Box */}
          <div className="relative flex-1">
            <span className="absolute inset-y-0 left-0 pl-3.5 flex items-center text-slate-400 text-sm">
              🔍
            </span>
            <input
              type="text"
              value={searchQuery}
              onChange={handleSearchChange}
              placeholder={t('menu.searchPlaceholder')}
              className="w-full pl-10 pr-4 py-2.5 rounded-xl sm:rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-xs sm:text-sm focus:outline-hidden focus:border-orange-500"
            />
            {searchQuery && (
              <button
                onClick={() => handleSearchChange({ target: { value: '' } })}
                className="absolute inset-y-0 right-0 pr-3.5 flex items-center text-slate-400 hover:text-slate-600 text-xs"
              >
                ✕
              </button>
            )}
          </div>

          {/* Sort Dropdown */}
          <div className="flex items-center space-x-2">
            <span className="text-xs font-bold text-slate-500 dark:text-slate-400 whitespace-nowrap">
              {t('menu.sortBy')}
            </span>
            <select
              value={sortBy}
              onChange={(e) => onIntent(MenuIntent.setSortBy(e.target.value))}
              className="flex-1 sm:flex-none px-3 py-2 rounded-xl sm:rounded-2xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white text-xs font-bold focus:outline-hidden focus:border-orange-500 cursor-pointer"
            >
              <option value="popular">{t('menu.sortPopular')}</option>
              <option value="price-low">{t('menu.sortPriceLow')}</option>
              <option value="price-high">{t('menu.sortPriceHigh')}</option>
              <option value="name">{t('menu.sortName')}</option>
            </select>
          </div>
        </div>

        {/* Category Pills */}
        <div className="flex items-center space-x-1.5 sm:space-x-2 overflow-x-auto pt-1 pb-1 -mx-3.5 sm:-mx-5 px-3.5 sm:px-5 scroll-smooth scrollbar-none overscroll-x-contain">
          <button
            onClick={() => handleCategoryChange('ALL')}
            className={`px-3 sm:px-3.5 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-all flex items-center space-x-1.5 shrink-0 ${
              selectedCategory === 'ALL'
                ? 'bg-orange-500 text-white shadow-xs'
                : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700'
            }`}
          >
            <span>{t('menu.allFoods')}</span>
            <span className="text-[10px] opacity-75">({foods.length})</span>
          </button>

          {categories.map((cat) => {
            const count = foods.filter(
              (f) => f.categoryName?.toLowerCase() === cat.name.toLowerCase()
            ).length;

            return (
              <button
                key={cat._id || cat.id || cat.name}
                onClick={() => handleCategoryChange(cat.name)}
                className={`px-3 sm:px-3.5 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-all flex items-center space-x-1.5 shrink-0 ${
                  selectedCategory === cat.name
                    ? 'bg-orange-500 text-white shadow-xs'
                    : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700'
                }`}
              >
                <span>{cat.name}</span>
                {count > 0 && <span className="text-[10px] opacity-75">({count})</span>}
              </button>
            );
          })}

          {selectedCategory !== 'ALL' && (
            <Link
              to={getCategoryDetailRoute(
                categories.find((c) => c.name === selectedCategory)?.id || selectedCategory
              )}
              className="px-3 py-1.5 rounded-xl bg-orange-100 dark:bg-orange-950/60 text-orange-600 dark:text-orange-400 text-xs font-bold whitespace-nowrap hover:bg-orange-200 transition-all shrink-0 flex items-center space-x-1"
            >
              <span>{t('categories.exploreDishes')}</span>
              <span>→</span>
            </Link>
          )}
        </div>
      </div>

      {/* Dishes Catalog Grid */}
      {loading ? (
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-6">
          {[1, 2, 3, 4, 5, 6, 7, 8].map((n) => (
            <div
              key={n}
              className="bg-white dark:bg-slate-900 rounded-2xl sm:rounded-3xl p-3 sm:p-4 border border-slate-200 dark:border-slate-800 space-y-3 sm:space-y-4 animate-pulse"
            >
              <div className="h-36 sm:h-44 bg-slate-200 dark:bg-slate-800 rounded-xl sm:rounded-2xl" />
              <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded-md w-3/4" />
              <div className="h-3 bg-slate-200 dark:bg-slate-800 rounded-md w-1/2" />
              <div className="flex justify-between items-center pt-2">
                <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded-md w-12" />
                <div className="h-6 sm:h-8 bg-slate-200 dark:bg-slate-800 rounded-lg sm:rounded-xl w-14 sm:w-20" />
              </div>
            </div>
          ))}
        </div>
      ) : processedFoods.length === 0 ? (
        <div className="text-center py-12 sm:py-16 bg-white dark:bg-slate-900 rounded-2xl sm:rounded-3xl border border-slate-200 dark:border-slate-800 p-6 sm:p-8 space-y-3">
          <span className="text-3xl sm:text-4xl">🍽️</span>
          <h3 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white">
            {t('menu.noFoodsFound')}
          </h3>
          <p className="text-xs text-slate-500">
            {t('menu.noFoodsSubtitle')}
          </p>
          <button
            onClick={() => setSearchParams({})}
            className="mt-2 px-4 py-2 rounded-xl bg-orange-500 text-white font-bold text-xs"
          >
            {t('menu.clearFilters')}
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-6">
          {processedFoods.map((food) => (
            <FoodCard
              key={food.id}
              food={food}
              onSelect={(selected) => onIntent(MenuIntent.selectFood(selected))}
            />
          ))}
        </div>
      )}

      {/* Food Detail Modal */}
      {selectedFood && (
        <FoodDetailModal
          food={selectedFood}
          onClose={() => onIntent(MenuIntent.clearSelectedFood())}
        />
      )}
    </div>
  );
}
