// food_order_admin/src/features/orders/components/OrderDetailModal.vue
<script setup lang="ts">
import { useOrdersStore } from '../stores/orders_store';
import type { OrderStatus } from '../../../domain/orders/entities/order_entity';
import {
  X,
  MapPin,
  Phone,
  User,
  Clock,
  Printer,
  FileText,
  AlertCircle,
} from 'lucide-vue-next';

const ordersStore = useOrdersStore();

const statusSteps: { key: OrderStatus; label: string }[] = [
  { key: 'pending', label: 'Pending' },
  { key: 'preparing', label: 'Preparing' },
  { key: 'on_delivery', label: 'On Delivery' },
  { key: 'delivered', label: 'Delivered' },
];
</script>

<template>
  <div
    v-if="ordersStore.isDetailModalOpen && ordersStore.selectedOrder"
    class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md transition-opacity"
  >
    <div
      class="bg-slate-900 border border-slate-800 rounded-3xl max-w-2xl w-full max-h-[90vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200"
    >
      <div class="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-900/80">
        <div class="flex items-center gap-3">
          <div class="p-2 rounded-xl bg-orange-500/10 text-orange-400 border border-orange-500/20">
            <FileText class="w-5 h-5" />
          </div>
          <div>
            <div class="flex items-center gap-2">
              <h2 class="text-lg font-bold text-white font-display">
                Order {{ ordersStore.selectedOrder.orderNumber }}
              </h2>
              <span class="text-xs px-2.5 py-0.5 rounded-full font-semibold bg-orange-500/20 text-orange-400 border border-orange-500/30">
                {{ ordersStore.selectedOrder.status }}
              </span>
            </div>
            <p class="text-xs text-slate-400">Placed {{ ordersStore.selectedOrder.createdAt }}</p>
          </div>
        </div>

        <button
          @click="ordersStore.closeOrderDetail()"
          class="w-8 h-8 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-white flex items-center justify-center transition"
        >
          <X class="w-4 h-4" />
        </button>
      </div>

      <div class="flex-1 overflow-y-auto p-6 space-y-6">
        <div>
          <label class="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
            Change Order Status
          </label>
          <div class="grid grid-cols-4 gap-2">
            <button
              v-for="step in statusSteps"
              :key="step.key"
              @click="ordersStore.updateOrderStatus(ordersStore.selectedOrder!.id, step.key)"
              :class="[
                'py-2 px-3 rounded-xl text-xs font-bold border transition text-center',
                ordersStore.selectedOrder.status === step.key
                  ? 'bg-orange-500 text-white border-orange-400 shadow-lg shadow-orange-500/25'
                  : 'bg-slate-800/60 text-slate-400 border-slate-700/60 hover:text-white hover:bg-slate-800'
              ]"
            >
              {{ step.label }}
            </button>
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 rounded-2xl bg-slate-800/40 border border-slate-800/80">
          <div class="space-y-2">
            <div class="flex items-center gap-2 text-xs text-slate-400 font-semibold uppercase">
              <User class="w-3.5 h-3.5 text-orange-400" />
              <span>Customer</span>
            </div>
            <div class="text-sm font-bold text-white">{{ ordersStore.selectedOrder.customerName }}</div>
            <div class="text-xs text-slate-300 flex items-center gap-1.5">
              <Phone class="w-3 h-3 text-slate-400" />
              <span>{{ ordersStore.selectedOrder.customerPhone }}</span>
            </div>
          </div>

          <div class="space-y-2">
            <div class="flex items-center gap-2 text-xs text-slate-400 font-semibold uppercase">
              <MapPin class="w-3.5 h-3.5 text-orange-400" />
              <span>Delivery Address</span>
            </div>
            <div class="text-xs text-slate-200 leading-relaxed">
              {{ ordersStore.selectedOrder.customerAddress }}
            </div>
            <div class="text-[11px] text-slate-400 flex items-center gap-1">
              <Clock class="w-3 h-3 text-orange-400" />
              <span>Est. Prep & Delivery: {{ ordersStore.selectedOrder.estimatedDeliveryMinutes }}m</span>
            </div>
          </div>
        </div>

        <div
          v-if="ordersStore.selectedOrder.notes"
          class="flex items-start gap-2.5 p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 text-xs text-amber-300"
        >
          <AlertCircle class="w-4 h-4 shrink-0 mt-0.5 text-amber-400" />
          <div>
            <span class="font-bold">Customer Notes: </span>
            {{ ordersStore.selectedOrder.notes }}
          </div>
        </div>

        <div>
          <h4 class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
            Items Ordered ({{ ordersStore.selectedOrder.items.length }})
          </h4>
          <div class="space-y-2.5">
            <div
              v-for="item in ordersStore.selectedOrder.items"
              :key="item.id"
              class="flex items-center justify-between p-3 rounded-xl bg-slate-800/40 border border-slate-800/60"
            >
              <div class="flex items-center gap-3">
                <img
                  v-if="item.image"
                  :src="item.image"
                  :alt="item.name"
                  class="w-12 h-12 rounded-xl object-cover"
                />
                <div>
                  <h5 class="text-xs font-bold text-white">{{ item.name }}</h5>
                  <div class="text-[11px] text-slate-400">
                    Qty: <span class="font-bold text-slate-200">{{ item.quantity }}</span> &times; ${{ item.price.toFixed(2) }}
                  </div>
                  <div v-if="item.specialInstructions" class="text-[10px] text-orange-400 font-medium">
                    Note: {{ item.specialInstructions }}
                  </div>
                </div>
              </div>
              <div class="text-sm font-bold text-white">
                ${{ (item.price * item.quantity).toFixed(2) }}
              </div>
            </div>
          </div>
        </div>

        <div class="p-4 rounded-2xl bg-slate-800/30 border border-slate-800/60 space-y-2 text-xs">
          <div class="flex justify-between text-slate-400">
            <span>Subtotal</span>
            <span class="text-white">${{ ordersStore.selectedOrder.subtotal.toFixed(2) }}</span>
          </div>
          <div class="flex justify-between text-slate-400">
            <span>Delivery Fee</span>
            <span class="text-white">${{ ordersStore.selectedOrder.deliveryFee.toFixed(2) }}</span>
          </div>
          <div class="flex justify-between text-slate-400">
            <span>Driver Tip</span>
            <span class="text-white">${{ ordersStore.selectedOrder.driverTip.toFixed(2) }}</span>
          </div>
          <div v-if="ordersStore.selectedOrder.discount > 0" class="flex justify-between text-emerald-400">
            <span>Voucher Discount</span>
            <span>-${{ ordersStore.selectedOrder.discount.toFixed(2) }}</span>
          </div>
          <div class="pt-2 border-t border-slate-700/60 flex justify-between text-sm font-bold text-white">
            <span>Total Amount</span>
            <span class="text-orange-400 text-base font-display">
              ${{ ordersStore.selectedOrder.total.toFixed(2) }}
            </span>
          </div>
        </div>
      </div>

      <div class="px-6 py-4 border-t border-slate-800 flex items-center justify-between bg-slate-900/80">
        <button
          @click="ordersStore.updateOrderStatus(ordersStore.selectedOrder!.id, 'cancelled')"
          class="px-4 py-2 rounded-xl bg-rose-500/10 text-rose-400 border border-rose-500/20 hover:bg-rose-500 hover:text-white text-xs font-semibold transition"
        >
          Cancel Order
        </button>

        <div class="flex items-center gap-2">
          <button
            onclick="window.print()"
            class="px-4 py-2 rounded-xl bg-slate-800 text-slate-300 hover:text-white hover:bg-slate-700 text-xs font-semibold flex items-center gap-1.5 transition"
          >
            <Printer class="w-3.5 h-3.5" />
            <span>Print Docket</span>
          </button>
          <button
            @click="ordersStore.closeOrderDetail()"
            class="px-5 py-2 rounded-xl bg-orange-500 hover:bg-orange-600 text-white text-xs font-bold transition shadow-lg shadow-orange-500/20"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// food_order_web/src/features/orders/components/order_detail_modal.jsx
import { StatusPill } from './status_pill';

export function OrderDetailModal({ order, onClose, onUpdateStatus }) {
  if (!order) return null;

  const orderId = order._id || order.id || 'N/A';
  const shortId = orderId.length > 6 ? orderId.substring(orderId.length - 6).toUpperCase() : orderId;
  const status = (order.status || 'pending').toLowerCase();
  const totalAmount = Number(order.totalAmount || 0).toFixed(2);
  const paymentMethod = (order.paymentMethod || 'cash').toUpperCase();
  const items = Array.isArray(order.items) ? order.items : [];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 dark:bg-black/75 backdrop-blur-xs p-4 animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-800 rounded-3xl max-w-lg w-full max-h-[90vh] overflow-hidden flex flex-col shadow-2xl border border-slate-200 dark:border-slate-700 transition-colors">
        {/* Header */}
        <div className="px-6 py-5 border-b border-slate-100 dark:border-slate-700 flex items-center justify-between bg-slate-50/50 dark:bg-slate-900/40">
          <div>
            <div className="flex items-center space-x-2">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white">Order #{shortId}</h2>
              <StatusPill status={status} />
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              {order.createdAt ? new Date(order.createdAt).toLocaleString() : 'Recent Order'}
            </p>
          </div>

          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-500 dark:text-slate-300 flex items-center justify-center transition-colors cursor-pointer"
          >
            ✕
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Delivery Info */}
          <div className="bg-slate-50 dark:bg-slate-900/60 rounded-2xl p-4 border border-slate-100 dark:border-slate-700">
            <h3 className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-2">
              Delivery Address
            </h3>
            <p className="text-sm font-semibold text-slate-900 dark:text-white leading-relaxed">
              {order.deliveryAddress || 'No address provided'}
            </p>
          </div>

          {/* Itemized Order List */}
          <div>
            <h3 className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-3">
              Order Items ({items.length})
            </h3>
            <div className="space-y-3">
              {items.map((item, idx) => {
                const name = item.foodName || item.food?.name || 'Dish Item';
                const qty = item.quantity || 1;
                const price = Number(item.price || item.food?.price || 0).toFixed(2);
                const itemTotal = (qty * (item.price || item.food?.price || 0)).toFixed(2);

                return (
                  <div
                    key={idx}
                    className="flex items-center justify-between py-2 border-b border-slate-100 dark:border-slate-700/60 last:border-b-0"
                  >
                    <div className="flex items-center space-x-3">
                      <div className="w-8 h-8 rounded-lg bg-orange-100 dark:bg-orange-950/60 text-orange-700 dark:text-orange-400 font-bold text-xs flex items-center justify-center">
                        {qty}x
                      </div>
                      <div>
                        <div className="text-sm font-semibold text-slate-800 dark:text-slate-200">{name}</div>
                        <div className="text-xs text-slate-400 dark:text-slate-500">${price} each</div>
                      </div>
                    </div>
                    <div className="text-sm font-bold text-slate-900 dark:text-white">${itemTotal}</div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Bill Summary */}
          <div className="pt-4 border-t border-slate-100 dark:border-slate-700 space-y-2 text-sm">
            <div className="flex justify-between text-slate-600 dark:text-slate-400">
              <span>Payment Method</span>
              <span className="font-semibold text-slate-800 dark:text-slate-200">
                {paymentMethod === 'KHQR' ? 'ABA KHQR' : paymentMethod}
              </span>
            </div>
            <div className="flex justify-between text-slate-600 dark:text-slate-400">
              <span>Payment Status</span>
              <span className="font-semibold text-emerald-600 dark:text-emerald-400 uppercase text-xs">
                {order.paymentStatus || 'Verified'}
              </span>
            </div>
            <div className="flex justify-between text-base font-extrabold text-slate-900 dark:text-white pt-2 border-t border-slate-100 dark:border-slate-700">
              <span>Total Bill</span>
              <span className="text-orange-600 dark:text-orange-400 text-lg">${totalAmount}</span>
            </div>
          </div>

          {/* Status Management */}
          <div>
            <h3 className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-3">
              Update Order Status
            </h3>
            <div className="grid grid-cols-2 gap-2 text-xs">
              <button
                onClick={() => onUpdateStatus(orderId, 'preparing')}
                className={`py-2 px-3 rounded-xl font-semibold border transition-all cursor-pointer ${
                  status === 'preparing'
                    ? 'bg-orange-50 dark:bg-orange-950/60 border-orange-300 dark:border-orange-800 text-orange-700 dark:text-orange-300 font-bold'
                    : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800'
                }`}
              >
                🍳 Cooking (Preparing)
              </button>
              <button
                onClick={() => onUpdateStatus(orderId, 'on_the_way')}
                className={`py-2 px-3 rounded-xl font-semibold border transition-all cursor-pointer ${
                  status === 'on_the_way'
                    ? 'bg-indigo-50 dark:bg-indigo-950/60 border-indigo-300 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 font-bold'
                    : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800'
                }`}
              >
                🛵 Dispatch Driver
              </button>
              <button
                onClick={() => onUpdateStatus(orderId, 'delivered')}
                className={`py-2 px-3 rounded-xl font-semibold border transition-all cursor-pointer ${
                  status === 'delivered'
                    ? 'bg-emerald-50 dark:bg-emerald-950/60 border-emerald-300 dark:border-emerald-800 text-emerald-700 dark:text-emerald-300 font-bold'
                    : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800'
                }`}
              >
                ✅ Mark Delivered
              </button>
              <button
                onClick={() => onUpdateStatus(orderId, 'cancelled')}
                className={`py-2 px-3 rounded-xl font-semibold border transition-all cursor-pointer ${
                  status === 'cancelled'
                    ? 'bg-rose-50 dark:bg-rose-950/60 border-rose-300 dark:border-rose-800 text-rose-700 dark:text-rose-300 font-bold'
                    : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-700 text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/30'
                }`}
              >
                ❌ Cancel Order
              </button>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate-50 dark:bg-slate-900/60 border-t border-slate-100 dark:border-slate-700 flex justify-end">
          <button
            onClick={onClose}
            className="bg-slate-900 dark:bg-orange-500 hover:bg-slate-800 dark:hover:bg-orange-600 text-white font-semibold text-xs py-2.5 px-6 rounded-xl transition-colors cursor-pointer"
          >
            Close Details
          </button>
        </div>
      </div>
    </div>
  );
}
